### ISSUE TITLE
Error: define cannot be used indirect

### ISSUE THREAD

**Issue by osequi** [bbc/color-contrast-checker#15]
I'm trying to import this package into React.
None of these works:

```js
import { ColorContrastChecker } from "color-contrast-checker";
import ColorContrastChecker from "color-contrast-checker";
```

Thank you.

**Comment by plumpNation** [comment]
I am also failing to import this library.

```
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

Is it only available for requirejs?

**Comment by Qambar** [comment]
Hey Guys, sorry for the delay, I have just seen this issue, let me try to reproduce it on myself and see if I can fix that. You are also welcome to raise a PR to fix this if you find the solution before me. This repository is open for contributions.
