### ISSUE TITLE
Webpage Url Checker - Feature Request

### ISSUE THREAD

**Issue by Qambar** [bbc/color-contrast-checker#3]
@nasreenshaik : "Is there a way were we can send the whole webpage url and get the output. writing for each component this way is very difficult"

**Comment by Qambar** [comment]
@nasreenshaik can you provide more details about your requirement, an example would help.

**Comment by nasreenshaik** [comment]
Sure :+1:

**Comment by nasreenshaik** [comment]
so, i need to test whole web page with color contrast issues. In my testing it is not possible for me to write colors of each component, pass it to CCC and get the output. which is difficult and also the code requires frequent changes to it. Instead, is there a way were i can run automation scripts and at the same time the page also gets tested in accessibility. 

When you see for w3cj plugin, it executes whole page with W3C validator and i call the at the end of each feature file for the page. same way i need to pass the page url and get the color contrast issues of that page(like Juicy contrast but to use in automation in js)

**Comment by Qambar** [comment]
So i see them as two separate projects. One is the plugin and another is the consumer of this plugin which would run like a headless test runner and compare body background with the text on page. It would help if you be more specific about your use case. 

What exactly are you testing on your pages ?

**Comment by nasreenshaik** [comment]
my use case is whenever my scripts navigates to one page, W3cjs validation should happen when the feature file says validate w3c , and Color Contrast checker should validate color contrast and give the output when feature file says validate color contrast of the page.

**Comment by Qambar** [comment]
Color Contrast Checker doesn't take pages as input. The input would be the fields or values. So i think what you are describing is out of scope of this project. I am closing this issue feel free to reopen it if you think i am misunderstood your request.
