### ISSUE TITLE
Dealing with shorthand color codes

### ISSUE THREAD

**Issue by AdamWills** [bbc/color-contrast-checker#4]
When using color shorthands (e.g. #fff), the tool doesn't recognize the input.

`Message:
    Invalid Color :#fff`

**Comment by Qambar** [comment]
Good spot, i can look into this today. It should be a simple fix.

**Comment by AdamWills** [comment]
Not sure if you want the dependency, but this is doing it: https://www.npmjs.com/package/color-shorthand-hex-to-six-digit

**Comment by Qambar** [comment]
According to [W3C CSS3 module: Color](https://www.w3.org/TR/2001/WD-css3-color-20010305#colorunits), to convert a shorthand to full color code, i just need to repeat the characters twice. 

So #123 will become #112233. Don't need to include an extra library to do that.

**Comment by Qambar** [comment]
Shorthand colors are now supported in version 1.4.0. So please update the version number in your code.
