### ISSUE TITLE
Is fontSize considered bold in the test?

### ISSUE THREAD

**Issue by ponori** [bbc/color-contrast-checker#6]
Wasn't sure what the definition was here since using bold seems to be a determining factor in contrast.

**Comment by Qambar** [comment]
> Text that is larger and has wider character strokes is easier to read at lower contrast. The contrast requirement for larger text is therefore lower. This allows authors to use a wider range of color choices for large text, which is helpful for design of pages, particularly titles. 18 point text or 14 point bold text is judged to be large enough to require a lower contrast ratio.

see: https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html
